import { getYjsValue } from "@syncedstore/core";
import * as Y from "yjs";
import store from "./store";

export default class AblyProvider {
  constructor(client, channel) {
    this.client = client;
    this.channel = client.channels.get(channel);
    // Get the y.js doc from the SyncedStore object.
    this.doc = getYjsValue(store);
    /*
      This is a client ID generated by y.js and has nothing to do with the Ably client
      that is being used to identify the users.
     */
    this.clientId = this.doc.clientID.toString();

    this.channel.subscribe(this.handleMessage.bind(this));
    // Mark the client as online.
    this.channel.presence.enter();

    this.doc.on("update", this.handleUpdate.bind(this));

    const state = Y.encodeStateVector(this.doc);
    this.channel.publish("syncStep1", state);
  }

  handleMessage(msg) {
    // Prevent glitches when starting Ably's service.
    if (msg.clientId === this.clientId) return;

    switch (msg.name) {
      case "syncStep1":
        const reply = Y.encodeStateAsUpdate(this.doc, new Uint8Array(msg.data));
        this.channel.publish("syncStep2", reply);
        break;
      case "syncStep2":
        Y.applyUpdate(this.doc, new Uint8Array(msg.data), this);
        break;
      case "update":
        Y.applyUpdate(this.doc, new Uint8Array(msg.data), this);
        break;
      default:
        console.error(`Unexpected message: ${msg.name}`);
        break;
    }
  }

  handleUpdate(update, origin) {
    if (origin !== this) {
      this.channel.publish("update", update);
    }
  }
}
